unique_ids:
  assets:
    standard-page.html: RXTUIXWMHOLLN7WFQJHC5U5UJ6JQDFLD
    theme.css: WWGVFFZPHUCXADFT467HL5RRV6RFVUQJ
  forms:
    Form1: BMNBSBISD54K75HXLUWRSQN3HZ3TQVPK
  modules: {}
  scripts: {}
  server_modules: {}
